version: "2"

services:

  nginx-bobcat:
      build: "./.docker/nginx-ubuntu/"
      container_name: "nginx-bobcat"
      volumes_from:
        - php-bobcat
      depends_on:
        - mysql-bobcat
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      networks:
        - bobcat-net

  mysql-bobcat:
      image: mysql:5.6
      container_name: "mysql-bobcat"
      environment:
        MYSQL_ROOT_PASSWORD: "root"
      ports:
        - "3306:3306"
      networks:
        - bobcat-net

  php-bobcat:
      build: "./.docker/php-ubuntu/"
      container_name: "php-bobcat"
      volumes:
        - php-bobcat-sync:/var/www/html:rw
      ports:
        - "9000:9000"
      networks:
        - bobcat-net


networks:
  bobcat-net:
    driver: bridge

volumes:
  php-bobcat-sync:
    external: true
